<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RLFoDjfService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RLFoDjf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RLFoDjf'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'player' => ['privates', '.errored..service_locator.RLFoDjf.App\\Domain\\MatchMaker\\Player\\Player', NULL, 'Cannot autowire service ".service_locator.RLFoDjf": it references class "App\\Domain\\MatchMaker\\Player\\Player" but no such service exists.'],
        ], [
            'player' => 'App\\Domain\\MatchMaker\\Player\\Player',
        ]);
    }
}
