<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RttZNcDService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RttZNcD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RttZNcD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'lobby' => ['privates', 'App\\Infra\\MatchMaker\\Lobby', 'getLobbyService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'lobby' => 'App\\Infra\\MatchMaker\\Lobby',
            'security' => '?',
        ]);
    }
}
