<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZoTCxjService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZoT_cxj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZoT_cxj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'formAuthenticator' => ['privates', 'App\\Infra\\Application\\Security\\UserAuthenticator', 'getUserAuthenticatorService', true],
            'guardHandler' => ['privates', 'security.authentication.guard_handler', 'getSecurity_Authentication_GuardHandlerService', true],
        ], [
            'encoder' => '?',
            'formAuthenticator' => 'App\\Infra\\Application\\Security\\UserAuthenticator',
            'guardHandler' => '?',
        ]);
    }
}
