<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDashboardControllerService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infra\MatchMaker\UserInterface\Controller\Admin\DashboardController' shared autowired service.
     *
     * @return \App\Infra\MatchMaker\UserInterface\Controller\Admin\DashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/DashboardControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractDashboardController.php';
        include_once \dirname(__DIR__, 4).'/src/Infra/MatchMaker/UserInterface/Controller/Admin/DashboardController.php';

        $container->services['App\\Infra\\MatchMaker\\UserInterface\\Controller\\Admin\\DashboardController'] = $instance = new \App\Infra\MatchMaker\UserInterface\Controller\Admin\DashboardController();

        $instance->setContainer(($container->privates['.service_locator.ETBPqPO'] ?? $container->load('get_ServiceLocator_ETBPqPOService'))->withContext('App\\Infra\\MatchMaker\\UserInterface\\Controller\\Admin\\DashboardController', $container));

        return $instance;
    }
}
