<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEncounterService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.IItci2N.App\Domain\MatchMaker\Encounter\Encounter' shared service.
     *
     * @return \App\Domain\MatchMaker\Encounter\Encounter
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.IItci2N": it references class "App\\Domain\\MatchMaker\\Encounter\\Encounter" but no such service exists.');
    }
}
