<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLobbyService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Infra\MatchMaker\Lobby' shared autowired service.
     *
     * @return \App\Infra\MatchMaker\Lobby
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Domain/MatchMaker/LobbyInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Domain/MatchMaker/Lobby.php';
        include_once \dirname(__DIR__, 4).'/src/Infra/MatchMaker/Lobby.php';

        return $container->privates['App\\Infra\\MatchMaker\\Lobby'] = new \App\Infra\MatchMaker\Lobby(($container->privates['App\\Infra\\MatchMaker\\Storage\\Repository\\EncounterRepository'] ?? $container->load('getEncounterRepositoryService')), ($container->privates['App\\Infra\\MatchMaker\\Storage\\Repository\\QueuingPlayerRepository'] ?? $container->load('getQueuingPlayerRepositoryService')));
    }
}
