<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatchCreateCommandService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Infra\MatchMaker\UserInterface\Command\MatchCreateCommand' shared autowired service.
     *
     * @return \App\Infra\MatchMaker\UserInterface\Command\MatchCreateCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Infra/MatchMaker/UserInterface/Command/MatchCreateCommand.php';

        $container->privates['App\\Infra\\MatchMaker\\UserInterface\\Command\\MatchCreateCommand'] = $instance = new \App\Infra\MatchMaker\UserInterface\Command\MatchCreateCommand(($container->privates['App\\Infra\\MatchMaker\\Lobby'] ?? $container->load('getLobbyService')), ($container->privates['monolog.logger'] ?? $container->getMonolog_LoggerService()));

        $instance->setName('app:encounters:create');

        return $instance;
    }
}
