<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPlayerService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.RLFoDjf.App\Domain\MatchMaker\Player\Player' shared service.
     *
     * @return \App\Domain\MatchMaker\Player\Player
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.RLFoDjf": it references class "App\\Domain\\MatchMaker\\Player\\Player" but no such service exists.');
    }
}
