<?php

namespace ContainerEbjO5io;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecurityControllerService extends App_Infra_Application_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Infra\User\UserInterface\Controller\SecurityController' shared autowired service.
     *
     * @return \App\Infra\User\UserInterface\Controller\SecurityController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Infra/User/UserInterface/Controller/SecurityController.php';

        $container->services['App\\Infra\\User\\UserInterface\\Controller\\SecurityController'] = $instance = new \App\Infra\User\UserInterface\Controller\SecurityController();

        $instance->setContainer(($container->privates['.service_locator.ULEwkxg'] ?? $container->load('get_ServiceLocator_ULEwkxgService'))->withContext('App\\Infra\\User\\UserInterface\\Controller\\SecurityController', $container));

        return $instance;
    }
}
