<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEbjO5io\App_Infra_Application_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEbjO5io/App_Infra_Application_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEbjO5io.legacy');

    return;
}

if (!\class_exists(App_Infra_Application_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEbjO5io\App_Infra_Application_KernelDevDebugContainer::class, App_Infra_Application_KernelDevDebugContainer::class, false);
}

return new \ContainerEbjO5io\App_Infra_Application_KernelDevDebugContainer([
    'container.build_hash' => 'EbjO5io',
    'container.build_id' => 'e950ea49',
    'container.build_time' => 1731582790,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEbjO5io');
