<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'admin' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'match_maker_index' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\EncounterController::index'], [], [['text', '/match/maker/']], [], []],
    'match_maker_new' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\EncounterController::new'], [], [['text', '/match/maker/new']], [], []],
    'match_maker_edit' => [['date', 'playerA', 'playerB'], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\EncounterController::edit'], [], [['text', '/score'], ['variable', '/', '[^/]++', 'playerB', true], ['text', '/vs'], ['variable', '/', '[^/]++', 'playerA', true], ['variable', '/', '[^/]++', 'date', true], ['text', '/match/maker']], [], []],
    'home' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'lobby' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\LobbyController::enterLobby'], [], [['text', '/lobby']], [], []],
    'lobbyPending' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\LobbyController::pendingLobby'], [], [['text', '/lobby/pending']], [], []],
    'lobbyExit' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\LobbyController::exitLobby'], [], [['text', '/lobby/exit']], [], []],
    'player_index' => [[], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\PlayerController::index'], [], [['text', '/player/']], [], []],
    'player_show' => [['id'], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\PlayerController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/player']], [], []],
    'player_edit' => [['id'], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\PlayerController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/player']], [], []],
    'player_delete' => [['id'], ['_controller' => 'App\\Infra\\MatchMaker\\UserInterface\\Controller\\PlayerController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/player']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Infra\\User\\UserInterface\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Infra\\User\\UserInterface\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'user_new' => [[], ['_controller' => 'App\\Infra\\User\\UserInterface\\Controller\\UserController::new'], [], [['text', '/user/new']], [], []],
];
